### ISSUE TITLE
Building script available?

### ISSUE THREAD

**Issue by alejandroandreu** [Davidnet/JetsonTFBuilds#1]
Hi @Davidnet ,

First off, thanks for making this repository available! It has saved me so much trouble to have these packages readily available :clap: 

I was wondering if you had a script where you described the process that you follow in order to generate them? I would like to build them myself so they are available in my APT repository so they can be installed in Docker images afterwards.

So far I tried following [1] with no luck for my TX2...

Cheers!

[1]: https://jany.st/post/2018-02-05-cross-compiling-tensorflow-for-jetson-tx1-with-bazel.html

**Comment by alejandroandreu** [comment]
Also, where did you get CUDA 9 & CUDNN 7 for the TX2 board? Using JetPack I can only get the CUDA 8 & CUDNN 6 :(

**Comment by Davidnet** [comment]
I'm going to upload the scripts in a few hours, with the new version of jetpack

**Comment by alejandroandreu** [comment]
Sounds awesome, thanks!

**Comment by andrey-moor** [comment]
@Davidnet still planning to upload the scripts?
